# libstemmer/mkinc_utf8.mak: List of stemming module source files
#
# This file is generated by mkmodules.pl from a list of module names.
# Do not edit manually.
#
# Modules included by this file are: danish, dutch, english, finnish, french,
# german, hungarian, italian, norwegian, porter, portuguese, romanian,
# russian, spanish, swedish, turkish

file( GLOB_RECURSE snowball_sources
  src_c/stem_UTF_8_danish.c 
  src_c/stem_UTF_8_dutch.c 
  src_c/stem_UTF_8_english.c 
  src_c/stem_UTF_8_finnish.c 
  src_c/stem_UTF_8_french.c 
  src_c/stem_UTF_8_german.c 
  src_c/stem_UTF_8_hungarian.c 
  src_c/stem_UTF_8_italian.c 
  src_c/stem_UTF_8_norwegian.c 
  src_c/stem_UTF_8_porter.c 
  src_c/stem_UTF_8_portuguese.c 
  src_c/stem_UTF_8_romanian.c 
  src_c/stem_UTF_8_russian.c 
  src_c/stem_UTF_8_spanish.c 
  src_c/stem_UTF_8_swedish.c 
  src_c/stem_UTF_8_turkish.c 
  runtime/api.c 
  runtime/utilities.c 
  libstemmer/libstemmer_utf8.c
)

